# Generated by Django 3.1.1 on 2020-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuserprofile',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
