# Generated by Django 3.2.8 on 2021-11-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20211130_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on', 'pk'],
            },
        ),
        migrations.AlterField(
            model_name='conversation',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Followers', 'Followers'), ('Mentionned', 'Mentionned')], default='Public', max_length=100),
        ),
        migrations.AlterField(
            model_name='reply',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Followers', 'Followers'), ('Mentionned', 'Mentionned')], default='Public', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='feed.Hashtag'),
        ),
        migrations.AddField(
            model_name='reply',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='feed.Hashtag'),
        ),
    ]
