# Generated by Django 3.2.8 on 2021-11-30 22:05

from django.db import migrations, models
import django.utils.timezone
import feed.validators


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20211130_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='schedule',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, validators=[feed.validators.validate_scheduling_date]),
        ),
        migrations.AddField(
            model_name='conversation',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='schedule',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, validators=[feed.validators.validate_scheduling_date]),
        ),
        migrations.AddField(
            model_name='reply',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Followers', 'Followers'), ('Mentionned', 'Mentionned')], default='Public', max_length=100),
        ),
        migrations.AlterField(
            model_name='reply',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Followers', 'Followers'), ('Mentionned', 'Mentionned')], default='Public', max_length=100),
        ),
    ]
